# Site
title:              Vinod Subramanian
bio:                'Music | Technology | Arts'
description:        "Masters student at the Center of Music Technology, Georgia Tech"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo2.png'
authorphoto:        'assets/img/logo3.png'
background:         'assets/img/placeholder-big2.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://VinodS7.github.io/
#url:                http://localhost:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   VinodS7-github-io

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              vinodv.ssubramanian@gmail.com
#twitter:            username
#facebook:           username
github-url:         VinodS7
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           vinod-subramanian-473784b6
#xing:              username
#instagram:          ashis.pati
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
